#!/usr/bin/env python
"""
FivcAdvisor CLI

Command-line interface for running FivcAdvisor graphs and tools.
"""

from uuid import uuid4
from typing import Optional
from pathlib import Path
import typer

from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

from fivcadvisor import graphs, tools, logs
from fivcadvisor.utils import create_output_dir

load_dotenv()

app = typer.Typer(
    name="FivcAdvisor",
    help="FivcAdvisor - "
    "Intelligent agent ecosystem for "
    "autonomous tool generation and "
    "dynamic crew orchestration",
    rich_markup_mode="rich",
)

console = Console()


@app.command()
def run(
    graph_type: str = typer.Argument("general", help="Type of graph to run"),
    query: Optional[str] = typer.Option(
        None,
        "--query",
        "-q",
        help="User query to process (if not provided, will prompt interactively)",
    ),
    output: Optional[Path] = typer.Option(
        None, "--output", "-o", help="Output file path"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show what would be done without executing"
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
):
    """
    Run a FivcAdvisor graph
    """
    console.print(
        Panel.fit(
            Text("FivcAdvisor Graph Runner", style="bold blue"),
            subtitle="Intelligent Agent Ecosystem",
        )
    )

    if query is None:
        query = typer.prompt("Enter your query")
        if not query:
            console.print("[red]❌ Query cannot be empty[/red]")
            raise typer.Exit(1)

    logs.register_default_events(logger=logs.agent_logger)  # build logs
    graphs.register_default_graphs(graphs_retriever=graphs.default_retriever)

    graph = graphs.default_retriever.get(graph_type)
    if not graph:
        console.print(f"[red]❌ Unknown graph type: {graph_type}[/red]")
        console.print("Available graphs: general, simple, complex")
        raise typer.Exit(1)

    if dry_run:
        console.print(f"[yellow]DRY RUN:[/yellow] Would run {graph_type} graph")
        if query:
            console.print(f"[yellow]Query:[/yellow] {query}")
        if output:
            console.print(f"[yellow]Output:[/yellow] {output}")
        return

    graph_run = graph(
        tools_retriever=tools.default_retriever,
        verbose=verbose,
        session_id=str(uuid4()),
    )

    with create_output_dir(base=output):
        try:
            graph_run.kickoff(inputs={"user_query": query})
            console.print("[green]✅ Graph completed successfully![/green]")
        except Exception as e:
            console.print(f"[red]❌ Error running graph: {e}[/red]")
            raise typer.Exit(1)


@app.command()
def plot(
    graph_type: str = typer.Argument("general", help="Type of graph to visualize"),
    output: Optional[Path] = typer.Option(
        None, "--output", "-o", help="Output file path"
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
):
    """
    Generate a visualization of a graph
    """

    console.print("[blue]Generating graph visualization...[/blue]")

    logs.register_default_events(logger=logs.agent_logger)  # build logs
    graphs.register_default_graphs(graphs_retriever=graphs.default_retriever)

    graph = graphs.default_retriever.get(graph_type)
    if not graph:
        console.print(f"[red]❌ Unknown graph type: {graph_type}[/red]")
        console.print("Available graphs: general, simple, complex")
        raise typer.Exit(1)

    graph_run = graph(
        tools_retriever=tools.default_retriever,
        verbose=verbose,
        session_id=str(uuid4()),
    )

    with create_output_dir(base=output) as d:
        try:
            graph_run.plot(graph_type)
            console.print(f"[green]✅ Visualization saved to {d}[/green]")
        except Exception as e:
            console.print(f"[red]❌ Error generating visualization: {e}[/red]")
            raise typer.Exit(1)


@app.command()
def clean():
    """
    Clean up temporary files generated by FivcAdvisor
    """
    console.print("[yellow]Cleaning up temporary files...[/yellow]")

    try:
        # Clean temp directories
        output_dir = create_output_dir()
        output_dir.cleanup(ignore_errors=False)
        console.print("[green]✅ Cleanup completed[/green]")

    except Exception as e:
        console.print(f"[red]❌ Error during cleanup: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def web(
    port: int = typer.Option(
        8501, "--port", "-p", help="Port to run the web interface on"
    ),
    host: str = typer.Option(
        "0.0.0.0", "--host", "-h", help="Host to bind the web interface to"
    ),
    debug: bool = typer.Option(False, "--debug", help="Run in debug mode"),
):
    """
    Launch the FivcAdvisor web interface using Streamlit
    """
    console.print(
        Panel.fit(
            Text("FivcAdvisor Web Interface", style="bold green"),
            subtitle="Starting Streamlit Application",
        )
    )

    try:
        import subprocess
        import sys
        import os

        console.print(f"[blue]Starting web interface at http://{host}:{port}[/blue]")
        console.print("[yellow]Press Ctrl+C to stop the server[/yellow]")

        # Get the path to the app module
        app_path = os.path.join(os.path.dirname(__file__), "app", "__init__.py")

        # Build streamlit command
        cmd = [
            sys.executable,
            "-m",
            "streamlit",
            "run",
            app_path,
            "--server.port",
            str(port),
            "--server.address",
            host,
            "--server.headless",
            "true",
            "--browser.gatherUsageStats",
            "false",
        ]

        if not debug:
            cmd.extend(["--logger.level", "error"])

        # Run streamlit
        subprocess.run(cmd, check=True)

    except KeyboardInterrupt:
        console.print("\n[yellow]Web interface stopped by user[/yellow]")
    except subprocess.CalledProcessError as e:
        console.print(f"[red]❌ Error starting web interface: {e}[/red]")
        console.print(
            "[yellow]Make sure Streamlit is installed: pip install streamlit[/yellow]"
        )
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]❌ Unexpected error: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def info():
    """
    Show information about FivcAdvisor
    """
    info_text = """
    [bold blue]FivcAdvisor[/bold blue]

    An intelligent agent ecosystem for autonomous tool generation,
    decision optimization, and dynamic crew orchestration.

    [bold]Features:[/bold]
    • Intelligent task assessment with consultant agents
    • Dynamic crew assembly based on task complexity
    • Autonomous tool generation and optimization
    • Event-driven graph orchestration

    [bold]Available Graphs:[/bold]
    • default - Intelligent task complexity assessment and execution

    [bold]Usage Examples:[/bold]
    fivcadvisor run general                                         # Interactive mode
    fivcadvisor run general --query "What is machine learning?"     # Programmatic mode
    fivcadvisor plot general
    fivcadvisor web                                                 # Launch web interface
    fivcadvisor clean                                               # Clean temporary files
    fivcadvisor info
    """

    console.print(Panel(info_text, title="FivcAdvisor", border_style="blue"))


def main():
    """
    Main entry point for the CLI
    """
    app()


if __name__ == "__main__":
    main()
