# Default Flow Configuration
# This configuration defines settings for the intelligent default flow system

flow_name: "default"
description: "Intelligent task assessment and execution using consultant agent evaluation"

# Default LLM settings
llm:
  model: "openai/gpt-4o-mini"
  temperature: 0.1
  max_tokens: 2000

# Agent configurations
agents:
  consultant:
    role: "Task Assessment Consultant"
    goal: "Assess task complexity and determine optimal execution approach"
    backstory: "Expert in analyzing task requirements and resource allocation"
    
  worker:
    role: "General Work Agent"
    goal: "Execute tasks efficiently using available tools"
    backstory: "Versatile agent capable of handling various operational tasks"
    
  director:
    role: "Team Director"
    goal: "Orchestrate specialized teams for complex task execution"
    backstory: "Strategic coordinator with expertise in team assembly and workflow design"

# Task complexity thresholds
complexity_assessment:
  simple_indicators:
    - "what is"
    - "how to"
    - "explain"
    - "define"
    - "simple"
    - "quick"
    - "basic"
    
  complex_indicators:
    - "analyze"
    - "research"
    - "create"
    - "develop"
    - "design"
    - "plan"
    - "multiple"
    - "various"
    - "comprehensive"
    - "detailed"
    - "complex"

# Tool selection rules
tools:
  basic:
    - "SerperDevTool"
    - "FileReadTool"
    - "FileWriterTool"
    
  research:
    - "SerperDevTool"
    - "WebsiteSearchTool"
    - "TavilySearchTool"
    
  analysis:
    - "CSVSearchTool"
    - "JSONSearchTool"
    - "CodeInterpreterTool"

# Execution rules
execution:
  word_count_threshold: 15  # Simple tasks typically have fewer words
  complexity_score_threshold: 2  # Threshold for complex task indicators
  
  simple_task_criteria:
    - "word_count < word_count_threshold"
    - "simplicity_score > complexity_score"
    
  complex_task_criteria:
    - "complexity_score > complexity_score_threshold"
    - "word_count > 20"

# Output settings
output:
  save_assessment: true
  save_execution_log: true
  visualization: true